# Generated by Django 5.1.7 on 2025-03-10 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filechunk',
            options={'ordering': ['chunk_number']},
        ),
        migrations.AddField(
            model_name='filechunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filechunk',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('corrupt', 'Corrupt')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='filechunk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
