# Generated by Django 5.1.7 on 2025-03-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_alter_filechunk_options_filechunk_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenode',
            name='access_key',
            field=models.CharField(default='minioadmin', max_length=255),
        ),
        migrations.AddField(
            model_name='filenode',
            name='bucket_name',
            field=models.CharField(default='hotel-files', max_length=255),
        ),
        migrations.AddField(
            model_name='filenode',
            name='console_port',
            field=models.IntegerField(default=9001),
        ),
        migrations.AddField(
            model_name='filenode',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filenode',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filenode',
            name='secret_key',
            field=models.CharField(default='minioadmin', max_length=255),
        ),
    ]
