# Generated by Django 5.1.7 on 2025-03-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_filenode_access_key_filenode_bucket_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filechunk',
            unique_together={('file', 'chunk_number', 'is_replica', 'node')},
        ),
    ]
