# Generated by Django 5.1.7 on 2025-03-17 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_update_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_replications', to='file_storage.filechunk')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_replications', to='file_storage.filenode')),
            ],
            options={
                'unique_together': {('chunk', 'target_node')},
            },
        ),
    ]
