services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - minio1
      - minio2
      - minio3

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=hotelfilesystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  minio1:
    image: minio/minio
    ports:
      - "9001:9000"
      - "9091:9090"
    volumes:
      - minio_data1:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9090" /data

  minio2:
    image: minio/minio
    ports:
      - "9002:9000"
      - "9092:9090"
    volumes:
      - minio_data2:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9090" /data

  minio3:
    image: minio/minio
    ports:
      - "9003:9000"
      - "9093:9090"
    volumes:
      - minio_data3:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9090" /data

volumes:
  postgres_data:
  minio_data1:
  minio_data2:
  minio_data3: